version: '3.8'

services:
  # MongoDB Database for Booking Service
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - booking_db_data:/data/db
      - ../../init/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # Mongo Express for MongoDB Management
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongo-db
    networks:
      - app_network

  # Booking Service
  booking-service:
    build:
      context: ../../booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongo-db:27017/booking-service?authSource=admin
    ports:
      - "8092:8092"
    depends_on:
      - mongo-db
    networks:
      - app_network

volumes:
  booking_db_data:

networks:
  app_network:
    driver: bridge