#  docker-compose -f docker-compose-single.yml up -d --build

version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-user
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./local-docker-file/postgres/init/user/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./db.migration/V1__init.sql:/docker-entrypoint-initdb.d/01-V1__init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8889:80"
    container_name: pgadmin-user
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password