#  docker-compose -f docker-compose-single.yml up -d --build

version: '3.8'
services:
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./db.migration:/docker-entrypoint-initdb.d
    networks:
      - app_network

  user-service:
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8090:8090"
    depends_on:
      - user-db
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.ca
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8889:80"
    networks:
      - app_network

volumes:
  user_db_data:

networks:
  app_network:
    driver: bridge